# Configuration file for data ingestion

# Root directory for storing artifacts
artifacts_root: artifacts

# Data ingestion settings
data_ingestion:
  root_dir: artifacts/data_ingestion  # Root directory for data ingestion artifacts
  source_URL: https://www.dropbox.com/s/qvglw8pqo16769f/pothole_dataset_v8.zip?dl=1  # URL of the data source
  local_data_file: artifacts/data_ingestion/data.zip  # Path to store the downloaded data file
  unzip_dir: artifacts/data_ingestion  # Directory to unzip the data file
