# Configuration file for data ingestion

# Root directory for storing artifacts
artifacts_root: artifacts

# Data ingestion settings
data_ingestion:
  root_dir: artifacts/data_ingestion  # Root directory for data ingestion artifacts
  source_URL: https://www.dropbox.com/s/qvglw8pqo16769f/pothole_dataset_v8.zip?dl=1  # URL of the data source
  local_data_file: artifacts/data_ingestion/data.zip  # Path to store the downloaded data file
  unzip_dir: artifacts/data_ingestion  # Directory to unzip the data file
  unzip_folder: dataset # Directory to unzip the

data_validation:
  data_dir: artifacts/data_ingestion  # Root directory for data validation artifacts
  data_folder: dataset # Stored data folder
  train_folder: train # Stored train folder
  val_folder: valid # Stored validation folder
  sub_dirs: # list of sub directories inside train and valid
  - images
  - labels

prepare_base_model:
  root_dir: artifacts/prepare_base_model  # Root directory for base model artifacts
  weights_dir: artifacts/prepare_base_model/weights # weights directory to store pretrained yolo weights
  download_url: https://github.com/ultralytics/assets/releases/download/v0.0.0/


training:
  root_dir: artifacts/training  # Root directory for training artifacts
  trained_model_dir: artifacts/training/runs # Training directory

validation:
  root_dir: artifacts/validation  # Root directory for validation artifacts
  validation_results_dir: artifacts/validation/runs # Validation directory